#!/bin/bash
help() {
    cat <<EOF
Usage: $(basename "$0") <command> [options]

Commands:
  run       Spwan a qemu vm for ./bzIamge.
  cp        Copy files to the virtual machine using 'copy2vm'.
  sh        Connect to the virtual machine shell using 'connect'.
  switch    Switch between different filesystem environments using 'switch'.
  zone      Create a new zone(debug enviroment)

Options:
  -h, --help  Display this help message and exit.

Examples:
  $(basename "$0") run
  $(basename "$0") cp /path/to/local/file
  $(basename "$0") sh
  $(basename "$0") switch default
  $(basename "$0") zone zone_v6.13 v6.13

EOF
}

# Handle help option
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    help
    exit 0
fi
# Check the first parameter using case
SCRIPT_DIR=$(dirname $(realpath $0))
# echo $SCRIPT_DIR
case "$1" in
    "")
        # Execute script for option1
        help
        ;;
    "run")
        shift
        $SCRIPT_DIR/run "$@"
        ;;
    "cp")
        shift
        $SCRIPT_DIR/copy2vm "$@"
        ;;
    "sh")
        shift
        $SCRIPT_DIR/connect "$@"
        ;;
    "pull")
        shift
        $SCRIPT_DIR/pull "$@"
        ;;
    "switch")
        shift
        $SCRIPT_DIR/switch_filesystem "$@"
        ;;
    "zone")
        shift
        $SCRIPT_DIR/zone "$@"
        ;;
    *)
        help
        ;;
esac