#!/bin/bash

# Check the first parameter using case
SCRIPT_DIR=$(dirname $(realpath $0))
# echo $SCRIPT_DIR
case "$1" in
    "")
        # Execute script for option1
        $SCRIPT_DIR/run
        ;;
    "run")
        # Execute script for option2
        $SCRIPT_DIR/run
        ;;
    "cp")
        $SCRIPT_DIR/copy2vm $2
        ;;
    "sh")
        $SCRIPT_DIR/connect
        ;;
    "pull")
        $SCRIPT_DIR/pull $2
        ;;
    "switch")
        $SCRIPT_DIR/switch $2
        ;;
    "zone")
        $SCRIPT_DIR/zone $2
        ;;
    *)
        echo "Invalid option or option not provided."
        echo "Usage: $0 <run|sh>"
        echo "or     $0 cp <file_path>"
        ;;
esac