#!/bin/bash

DIR=$(dirname $(realpath -s $0))
PDIR=$(dirname $DIR)
# set -x
if [ -z $1 ];
then
    echo "Missing Zone Name"
    exit
else
    ZN=$1
fi

if [ -d $PDIR/$ZN ]; then
  echo "Folder exists"
  exit
else
  cp  -a $PDIR/template $PDIR/$ZN
fi

if [ -z $2 ]; then 
    :
else
    if [ -d "$PDIR/kernel/kernel-$2" ]; then
        :
    else
        echo "[+] Kernel Version: " $2
        read -p "Do you want to download and compile the kernel? (y/n): " response
        if [[ "$response" =~ ^[Yy]$ ]]; then
            (
                cd "$PDIR/kernel" || exit 1
                ./build.sh $2
            )
        else
            :
        fi
    fi
    cp  "$PDIR/kernel/kernel-$2/vmlinux" $PDIR/$ZN
    cp  "$PDIR/kernel/kernel-$2/arch/x86/boot/bzImage" $PDIR/$ZN
    TMP="$PDIR/kernel/kernel-$2"
    sed -i "s|^\(KDIR =\).*|\1$TMP|" $PDIR/$ZN/module/Makefile
fi